### ISSUE TITLE
Fix Dependency

### ISSUE THREAD

**Issue by 9gix** [insert-coin/CloudyGameThinClient#1]
- [x] Remove hardcoded dependency path inside [the project file](https://github.com/insert-coin/CloudyGameThinClient/blob/c058df22dddf240cbdbbec67956024103cb8651b/CloudyGameThinClient/CloudyGameThinClient.vcxproj#L43-L44)

**Comment by 9gix** [comment]
I recommend the use of `$(SolutionDir)` and put all dependency inside `Library` folder under the project directory. And then `.gitignore` the `Library` folder.

**Comment by bloodelves88** [comment]
Fixed in 279b3b9ba2a3523e700698bb95fca73fd3c3010d
