### ISSUE TITLE
vlc.Instance() is NoneType on Mac

### ISSUE THREAD

**Issue by bloodelves88** [insert-coin/CloudyGameThinClient#24]
![img_20160218_180901](https://cloud.githubusercontent.com/assets/4394614/13565833/8074d3f6-e48d-11e5-8c07-f8098874c142.jpg)

Odd issue, with no solution found on Google.

Things to try to fix the issue:
- ~~Is VLC installed on the machine?~~
- ~~Try changing `vlcInstance = vlc.Instance()` to `vlcInstance = vlc.libvlc_new(0, None)`~~

**Comment by zeanne** [comment]
- VLC player is installed. 
- vlc.libvlc_new(0, None) returns NoneType as well.

**Comment by bloodelves88** [comment]
Not using VLC anymore
